# Generated by Django 4.1.4 on 2023-01-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_question_answer_question_choice_1_question_choice_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choice',
        ),
    ]
