# Generated by Django 4.1.4 on 2023-01-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_quiztaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizTaker',
        ),
    ]
