# Generated by Django 4.1.4 on 2023-01-19 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0011_delete_quiztaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_1', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_2', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_3', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_4', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(choices=[(models.CharField(blank=True, max_length=200, null=True), 'choice_1'), (models.CharField(blank=True, max_length=200, null=True), 'choice_2'), (models.CharField(blank=True, max_length=200, null=True), 'choice_3'), (models.CharField(blank=True, max_length=200, null=True), 'choice_4')], max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
