# Generated by Django 4.1.4 on 2023-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_scq_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scq',
            name='answer',
            field=models.CharField(choices=[(models.CharField(blank=True, max_length=200, null=True), 'choice 1'), (models.CharField(blank=True, max_length=200, null=True), 'choice 2'), (models.CharField(blank=True, max_length=200, null=True), 'choice 3'), (models.CharField(blank=True, max_length=200, null=True), 'choice 4')], max_length=200),
        ),
    ]
