# Generated by Django 4.1.4 on 2023-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_alter_scq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scq',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
