# Generated by Django 4.1.4 on 2023-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_booleanques_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='intques',
            name='marking',
            field=models.CharField(choices=[('nonegmarking', '+4/0'), ('negmarking', '+4/-1')], default='nonnegmarking', max_length=200),
        ),
        migrations.AddField(
            model_name='scq',
            name='marking',
            field=models.CharField(choices=[('nonegmarking', '+4/0'), ('negmarking', '+4/-1')], default='nonnegmarking', max_length=200),
        ),
    ]
