# Generated by Django 4.1.4 on 2023-01-19 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0020_rename_total_result_marks_scored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_1', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_1_ans', models.BooleanField(default=False)),
                ('choice_2', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_2_ans', models.BooleanField(default=False)),
                ('choice_3', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_3_ans', models.BooleanField(default=False)),
                ('choice_4', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_4_ans', models.BooleanField(default=False)),
                ('marking', models.CharField(choices=[('nonegmarking', '+4/0'), ('negmarking', '+4/-1')], default='nonnegmarking', max_length=200)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz')),
            ],
        ),
    ]
