# Generated by Django 4.1.4 on 2023-01-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0025_quiz_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateQuiz',
        ),
    ]
